<?php

declare(strict_types=1);

return [
    ['name' => '1.5L NIRVANA', 'unit' => 'PCS', 'units_per_pack' => 1, 'sku' => 'NIR-150CL-PCS'],
    ['name' => '1.5LTR PEPSI PET', 'unit' => 'PET', 'units_per_pack' => 12, 'sku' => 'PEP-PET-150CL-12'],
    ['name' => '25CL SUPA COMMANDO', 'unit' => 'CRATE', 'units_per_pack' => 24, 'sku' => 'SUP-25CL-CRT24'],
    ['name' => '30CL 5ALIVE LEMON', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => '5AL-LEM-30CL-12'],
    ['name' => '30CL 5ALIVE PULPY', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => '5AL-PUL-30CL-12'],
    ['name' => '35CL COCA-COLA PET', 'unit' => 'PET', 'units_per_pack' => 12, 'sku' => 'COK-PET-35CL-12'],
    ['name' => '35CL PET SPRITE', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'SPR-PET-35CL-12'],
    ['name' => '35CL PET FANTA', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'FAN-PET-35CL-12'],
    ['name' => '35CL PET FANTA ZERO', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'FAN-ZER-35CL-12'],
    ['name' => '35CL ZERO COKE', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'COK-ZER-35CL-12'],
    ['name' => '5ALIVE 85CL LEMON', 'unit' => 'PACK', 'units_per_pack' => 6, 'sku' => '5AL-LEM-85CL-06'],
    ['name' => '5ALIVE 85CL MANGO', 'unit' => 'PACK', 'units_per_pack' => 6, 'sku' => '5AL-MAN-85CL-06', 'stock_crates' => 1, 'cost_price' => 5000.00],
    ['name' => '5ALIVE BERRYBLAST 75CL', 'unit' => 'PACK', 'units_per_pack' => 6, 'sku' => '5AL-BER-75CL-06'],
    ['name' => '60CL ZERO COKE', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'COK-ZER-60CL-12'],
    ['name' => '78CL 5ALIVE CITRUS', 'unit' => 'PACK', 'units_per_pack' => 6, 'sku' => '5AL-CIT-78CL-06'],
    ['name' => '7UP PET MIDCAL 60CL', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => '7UP-PET-60CL-12', 'stock_crates' => 96, 'cost_price' => 4150.00, 'invoice_price' => 4150.00, 'rebate_base_price' => 4207.07, 'minimum_selling_price' => 4050.00, 'selling_price' => 4100.00, 'wholesale_price' => 4100.00, 'packaging_type' => 'PET', 'inventory_unit' => 'Pack', 'packs_per_pallet' => 154],
    ['name' => '90CL 5ALIVE TROPICAL', 'unit' => 'PACK', 'units_per_pack' => 6, 'sku' => '5AL-TRO-90CL-06'],
    ['name' => 'BIG COLA 250ML', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'BIG-COL-25CL-12', 'stock_crates' => 512, 'cost_price' => 1805.00],
    ['name' => 'BIG COLA 650ML', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'BIG-COL-65CL-12', 'stock_crates' => 2, 'cost_price' => 3330.00],
    ['name' => 'BIG TABLE WATER', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'BIG-WAT-PK12'],
    ['name' => 'CAN 33CL COCA-COLA', 'unit' => 'PACK', 'units_per_pack' => 24, 'sku' => 'COK-CAN-33CL-24', 'stock_crates' => 1, 'cost_price' => 10500.00],
    ['name' => 'CHAPMAN PET', 'unit' => 'PCS', 'units_per_pack' => 1, 'sku' => 'CHA-PET-PCS'],
    ['name' => 'CIELLO', 'unit' => 'PCS', 'units_per_pack' => 1, 'sku' => 'CIE-PCS-001', 'stock_crates' => 99, 'cost_price' => 3500.00],
    ['name' => 'CLIMAX', 'unit' => 'PACK', 'units_per_pack' => 0, 'sku' => 'CLI-PACK-001'],
    ['name' => 'COKE PET', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'COK-PET-PK12', 'stock_crates' => 531, 'cost_price' => 4650.00],
    ['name' => 'CWAY DISPENSER WATER', 'unit' => 'PACK', 'units_per_pack' => 1, 'sku' => 'CWAY-DISP-001'],
    ['name' => 'DUDU YOGURT', 'unit' => 'PACK', 'units_per_pack' => 0, 'sku' => 'DUD-YOG-PACK', 'stock_crates' => 754, 'cost_price' => 6730.00],
    ['name' => 'EMPTIES COCA COLA', 'unit' => 'CASE', 'units_per_pack' => 24, 'sku' => 'COK-EMP-CS24', 'stock_crates' => 310],
    ['name' => 'EVA 150CL WATER', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'EVA-WAT-150CL-12', 'stock_crates' => 25, 'cost_price' => 3650.00],
    ['name' => 'EVA WATER 75CL', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'EVA-WAT-75CL-12'],
    ['name' => 'FANTA 33CL CAN', 'unit' => 'CAN', 'units_per_pack' => 24, 'sku' => 'FAN-CAN-33CL-24'],
    ['name' => 'FANTA APPLE', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'FAN-APP-PK12'],
    ['name' => 'FANTA PET', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'FAN-PET-PK12', 'stock_crates' => 177, 'cost_price' => 4650.00],
    ['name' => 'IJABA 7UP & PEPSI EMPTIES', 'unit' => 'PCS', 'units_per_pack' => 1, 'sku' => 'EMP-7PP-PCS', 'stock_crates' => 123, 'cost_price' => 2070.00],
    ['name' => 'JACK DANIEL', 'unit' => 'PCS', 'units_per_pack' => 1, 'sku' => 'JAC-DAN-PCS', 'stock_crates' => 12, 'cost_price' => 22400.00],
    ['name' => 'LA AQUA TABLE WATER 75CLX12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'LAA-WAT-75CL-12'],
    ['name' => 'MAMA COCA-COLA 1LITRE', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'COK-MAM-100CL-12'],
    ['name' => 'MAMA ZERO FANTA 1LITRE', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'FAN-ZER-100CL-12'],
    ['name' => 'MONSTER ENERGY CAN', 'unit' => 'CAN', 'units_per_pack' => 1, 'sku' => 'MON-ENE-CAN', 'stock_crates' => 1, 'cost_price' => 21000.00],
    ['name' => 'NIRVANA', 'unit' => 'PACK', 'units_per_pack' => 0, 'sku' => 'NIR-PACK-001', 'stock_crates' => 913, 'cost_price' => 1346.00],
    ['name' => 'PEPSI FIZZ PET 40CL X 12', 'unit' => 'PCS', 'units_per_pack' => 12, 'sku' => 'PEP-FIZ-40CL-12', 'stock_crates' => 1, 'cost_price' => 2450.00],
    ['name' => 'PET 30CL SUPA KOMMANDO', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'SUP-PET-30CL-12', 'stock_crates' => 177, 'cost_price' => 2813.00, 'packaging_type' => 'PET', 'inventory_unit' => 'Pack', 'packs_per_pallet' => 224],
    ['name' => 'PET 35CL LACAZERA', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'LAC-PET-35CL-12'],
    ['name' => 'PET 360ML BIG COLA', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'BIG-PET-36CL-12', 'stock_crates' => 24, 'cost_price' => 2000.00],
    ['name' => 'PET 40CL 7UP FREE', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => '7UP-FRE-40CL-12'],
    ['name' => 'PET 40CL MIRINDA', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'MIR-PET-40CL-12'],
    ['name' => 'PET 40CL SCHWEPPES', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'SCH-PET-40CL-12'],
    ['name' => 'PET 50CL 7UP', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => '7UP-PET-50CL-12'],
    ['name' => 'PET 50CL LIPTON', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'LIP-PET-50CL-12'],
    ['name' => 'PET 50CL MIRINDA', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'MIR-PET-50CL-12'],
    ['name' => 'PET 50CL PEPSI', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'PEP-PET-50CL-12'],
    ['name' => 'PET 50CL TEEM BL', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'TEE-BL-50CL-12', 'stock_crates' => 119, 'cost_price' => 4150.00, 'packaging_type' => 'PET', 'inventory_unit' => 'Pack', 'packs_per_pallet' => 154],
    ['name' => 'PET 60CL PEPSI', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'PEP-PET-60CL-12', 'stock_crates' => 1126, 'cost_price' => 4150.00, 'invoice_price' => 4150.00, 'rebate_base_price' => 4207.07, 'minimum_selling_price' => 4050.00, 'selling_price' => 4100.00, 'wholesale_price' => 4100.00, 'packaging_type' => 'PET', 'inventory_unit' => 'Pack', 'packs_per_pallet' => 154],
    ['name' => 'PET 75CL AQUAFINA WATER', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'AQU-WAT-75CL-12'],
    ['name' => 'PET 7UP H2O TANG 40CLX12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => '7UP-H2O-40CL-12'],
    ['name' => 'PET BIG COLA 525ML', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'BIG-PET-525ML-12'],
    ['name' => 'PET CHIEF MALT 30CL', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'CHF-MAL-30CL-12'],
    ['name' => 'PET H2O TANG 40CLX12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'H2O-TAN-40CL-12'],
    ['name' => 'PET HYDR8 PINEBE30X12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'HYD-PIN-30CL-12'],
    ['name' => 'PET HYDR8 STRAWBERRY 30CL X 12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'HYD-STR-30CL-12'],
    ['name' => 'PET HYDR8 TAN 30CL X 12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'HYD-TAN-30CL-12'],
    ['name' => 'PET LIMCA 60CL', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'LIM-PET-60CL-12'],
    ['name' => 'PET MIR ORG 60CL X 12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'MIR-ORG-60CL-12', 'stock_crates' => 23, 'cost_price' => 4150.00],
    ['name' => 'PET MIR PINEAPPLE 60CL X 12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'MIR-PIN-60CL-12'],
    ['name' => 'PET PEPSI LITE 40CL', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'PEP-LIT-40CL-12'],
    ['name' => 'PET ROCKSTAR 50CLX12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'ROC-PET-50CL-12'],
    ['name' => 'PET SUPA COMMANDO 50CLX12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'SUP-PET-50CL-12', 'stock_crates' => 1024, 'cost_price' => 4022.00, 'minimum_selling_price' => 3930.00, 'packaging_type' => 'PET', 'inventory_unit' => 'Pack', 'packs_per_pallet' => 154],
    ['name' => 'PET TEEM SODA 50CLX12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'TEE-SOD-50CL-12'],
    ['name' => 'PET ZERO FANTA 60CL', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'FAN-ZER-60CL-12'],
    ['name' => 'PLANET COLA 35CL', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'PLA-COL-35CL-12'],
    ['name' => 'PLANET PET 50CLX12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'PLA-PET-50CL-12', 'stock_crates' => 1552, 'cost_price' => 3850.00],
    ['name' => 'PREDATOR GOLD', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'PRE-GOL-PK12', 'stock_crates' => 4, 'cost_price' => 4600.00],
    ['name' => 'PREDATOR MEAN GREEN', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'PRE-GRN-PK12'],
    ['name' => 'PULPY ORANGE 85CL', 'unit' => 'PACK', 'units_per_pack' => 6, 'sku' => 'PUL-ORA-85CL-06', 'stock_crates' => 25, 'cost_price' => 6000.00],
    ['name' => 'RBG 35CL SODA', 'unit' => 'CRATE', 'units_per_pack' => 24, 'sku' => 'RGB-SOD-35CL-24'],
    ['name' => 'RGB 35CL 7UP FREE', 'unit' => 'CRATE', 'units_per_pack' => 24, 'sku' => 'RGB-7UP-35CL-24', 'stock_crates' => 5, 'cost_price' => 2766.00],
    ['name' => 'RGB 35CL COCA COLA ULTRA', 'unit' => 'CRATE', 'units_per_pack' => 24, 'sku' => 'RGB-COK-35CL-24', 'stock_crates' => 81, 'cost_price' => 4400.00],
    ['name' => 'RGB 35CL LIMCA', 'unit' => 'CRATE', 'units_per_pack' => 24, 'sku' => 'RGB-LIM-35CL-24'],
    ['name' => 'RGB 35CL MIRINDA', 'unit' => 'CRATE', 'units_per_pack' => 24, 'sku' => 'RGB-MIR-35CL-24'],
    ['name' => 'RGB 35CL PEPSI', 'unit' => 'CRATE', 'units_per_pack' => 24, 'sku' => 'RGB-PEP-35CL-24'],
    ['name' => 'RGB 35CL PEPSI FREE', 'unit' => 'CRATE', 'units_per_pack' => 24, 'sku' => 'RGB-PEF-35CL-24'],
    ['name' => 'RGB 50CL 7UP BLUE', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-7UP-50CL-12', 'stock_crates' => 3, 'cost_price' => 5252.00, 'minimum_selling_price' => 4920.00, 'packaging_type' => 'RGB', 'inventory_unit' => 'Crate', 'packs_per_pallet' => 40],
    ['name' => 'RGB 50CL COCA-COLA', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-COK-50CL-12', 'stock_crates' => 11, 'cost_price' => 5800.00, 'minimum_selling_price' => 4920.00, 'packaging_type' => 'RGB', 'inventory_unit' => 'Crate', 'packs_per_pallet' => 40],
    ['name' => 'RGB 50CL FANTA', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-FAN-50CL-12', 'stock_crates' => 16, 'cost_price' => 5800.00, 'minimum_selling_price' => 4920.00, 'packaging_type' => 'RGB', 'inventory_unit' => 'Crate', 'packs_per_pallet' => 40],
    ['name' => 'RGB 50CL LIMCA', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-LIM-50CL-12', 'minimum_selling_price' => 4920.00, 'packaging_type' => 'RGB', 'inventory_unit' => 'Crate', 'packs_per_pallet' => 40],
    ['name' => 'RGB 50CL MIRINDA', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-MIR-50CL-12', 'minimum_selling_price' => 4920.00, 'packaging_type' => 'RGB', 'inventory_unit' => 'Crate', 'packs_per_pallet' => 40],
    ['name' => 'RGB 50CL MIRINDA BLUE', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-MIB-50CL-12', 'stock_crates' => 5, 'cost_price' => 5252.00, 'minimum_selling_price' => 4920.00, 'packaging_type' => 'RGB', 'inventory_unit' => 'Crate', 'packs_per_pallet' => 40],
    ['name' => 'RGB 50CL MIRINDA FREE', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-MIF-50CL-12', 'minimum_selling_price' => 4920.00, 'packaging_type' => 'RGB', 'inventory_unit' => 'Crate', 'packs_per_pallet' => 40],
    ['name' => 'RGB 50CL PEPSI BLUE', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-PEB-50CL-12', 'stock_crates' => 55, 'cost_price' => 5252.00, 'minimum_selling_price' => 4920.00, 'packaging_type' => 'RGB', 'inventory_unit' => 'Crate', 'packs_per_pallet' => 40],
    ['name' => 'RGB 50CL PEPSI LITE', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-PEL-50CL-12', 'stock_crates' => -3, 'cost_price' => 5256.00, 'minimum_selling_price' => 4920.00, 'packaging_type' => 'RGB', 'inventory_unit' => 'Crate', 'packs_per_pallet' => 40],
    ['name' => 'RGB 50CL SPRITE', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-SPR-50CL-12', 'stock_crates' => 29, 'cost_price' => 5700.00, 'minimum_selling_price' => 4920.00, 'packaging_type' => 'RGB', 'inventory_unit' => 'Crate', 'packs_per_pallet' => 40],
    ['name' => 'RGB 7UP FREE 50CL', 'unit' => 'CRATE', 'units_per_pack' => 12, 'sku' => 'RGB-7UF-50CL-12'],
    ['name' => 'SCHWEPPES 33CL CAN', 'unit' => 'CAN', 'units_per_pack' => 24, 'sku' => 'SCH-CAN-33CL-24'],
    ['name' => 'SPRITE 33CL CAN', 'unit' => 'CAN', 'units_per_pack' => 24, 'sku' => 'SPR-CAN-33CL-24'],
    ['name' => 'SPRITE PET', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'SPR-PET-PK12', 'stock_crates' => 230, 'cost_price' => 4650.00],
    ['name' => 'VYBE CHAPMAN 30CL X 12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'VYB-CHA-30CL-12'],
    ['name' => 'VYBE GINGER 30CL X 12', 'unit' => 'PACK', 'units_per_pack' => 12, 'sku' => 'VYB-GIN-30CL-12'],
];
